# Generated by Django 4.2.15 on 2024-09-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=255, unique=True)),
                ('parent_dept', models.CharField(max_length=255, unique=True)),
                ('dept_is_enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
