# Generated by Django 4.2.11 on 2024-09-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0003_user_workshiftsmodel_usershifttimingsmodel_timeentry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designationmodel',
            name='department',
        ),
        migrations.AlterField(
            model_name='employees',
            name='functional_superior',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='hr_superior',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='immediate_superior',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
