# Generated by Django 5.1.1 on 2024-09-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0005_authenticationmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthenticationModel',
        ),
        migrations.AlterField(
            model_name='employees',
            name='emp_is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
