# Generated by Django 5.1 on 2024-09-12 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0005_authenticationmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthenticationModel',
        ),
    ]
